[settings]
experimental = true
cargo_binstall = true
[tools]
node = "latest"
rust = "latest"
"cargo:cargo-binstall" = "latest"
"cargo:eza" = "latest"
usage = "latest"
"npm:cdk" = "latest"
awscli = "latest"
aws-vault = "latest"
bat = "latest"
delta = "latest"
aws-copilot = "latest"
"pipx:powerline-status" = "latest"
github-cli = "latest"
1password-cli = "latest"
"cargo:fd-find" = "latest"
"cargo:ripgrep" = "latest"
"cargo:cargo-update" = "latest"
aws-sso-cli = "latest"
"cargo:bottom" = "latest"
